name: Soul City Worship
favicon: null
layout_spectrum: 0.24667
typography_spectrum: 0.56445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#ececec'
    - '#302827'
    - '#78333a'
    - '#d09786'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
