name: Soul City Worship
favicon: null
layout_spectrum: 0.46672144532203674
typography_spectrum: 0.5387271319050342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.28506595897488296
  lightness: 0.13743410794995725
  saturation: 0.1671075818594545
  rhythmicContrast: 0.43833916867151856
purpose: []
